# Generated by Django 5.2 on 2025-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adverts/'),
        ),
        migrations.DeleteModel(
            name='AdvertImage',
        ),
    ]
