# Generated by Django 5.2 on 2025-04-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('awarding_body', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qualifications', models.ManyToManyField(to='quality.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50)),
                ('unit_title', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField()),
                ('assessment_date', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('R', 'Referred')], max_length=1)),
                ('feedback', models.TextField()),
                ('evidence', models.FileField(upload_to='assessments/evidence/')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.assessor')),
            ],
        ),
        migrations.CreateModel(
            name='EQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarding_body', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EQAVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('P', 'Physical Visit'), ('R', 'Remote Visit')], max_length=1)),
                ('agenda', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('report', models.FileField(blank=True, null=True, upload_to='eqa/reports/')),
                ('eqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.eqa')),
            ],
        ),
        migrations.CreateModel(
            name='IQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qualifications', models.ManyToManyField(to='quality.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='IQASample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('decision', models.CharField(choices=[('A', 'Approved'), ('R', 'Revisions Required'), ('I', 'Invalid')], max_length=1)),
                ('feedback_to_assessor', models.TextField()),
                ('verification_record', models.FileField(upload_to='iqa/records/')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.assessment')),
                ('iqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.iqa')),
            ],
        ),
        migrations.CreateModel(
            name='EQASample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('outcome', models.CharField(choices=[('S', 'Satisfactory'), ('A', 'Action Required'), ('U', 'Unsatisfactory')], max_length=1)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.assessment')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.eqavisit')),
                ('iqa_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quality.iqasample')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField()),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.assessor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qualifications', models.ManyToManyField(to='quality.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.learner'),
        ),
        migrations.CreateModel(
            name='IQASamplingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sample_size_percent', models.IntegerField()),
                ('criteria', models.TextField()),
                ('plan_document', models.FileField(upload_to='iqa/plans/')),
                ('iqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.iqa')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualification'),
        ),
    ]
