# Generated by Django 5.2 on 2025-04-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='LearningOutcome',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
