# Generated by Django 5.2 on 2025-04-20 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent by all users in seconds')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course'], name='course_anal_course__9e8662_idx'), models.Index(fields=['last_updated'], name='course_anal_last_up_f7c1aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='courses.enrollment')),
                ('lesson', models.ForeignKey(limit_choices_to={'lesson_type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='courses.lesson')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'lesson'], name='course_anal_enrollm_e7a0a2_idx'), models.Index(fields=['attempt_date'], name='course_anal_attempt_6c0179_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'lesson'], name='course_anal_enrollm_d2be8c_idx'), models.Index(fields=['last_accessed'], name='course_anal_last_ac_ed60fe_idx')],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
