# Generated by Django 5.2 on 2025-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira (₦)'), ('USD', 'Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'Pound (£)'), ('JPY', 'Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Yuan (¥)'), ('INR', 'Indian Rupee (₹)')], default='NGN', max_length=3),
        ),
    ]
