# Generated by Django 5.2 on 2025-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_prerequisite_course_course_learning_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='1 hour', help_text='Duration in minutes', max_length=20),
        ),
    ]
