# Generated by Django 5.2 on 2025-04-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagetype'),
        ),
    ]
